### ISSUE TITLE
Too slow in inserting large data

### ISSUE THREAD

**Issue by KiraKmp** [simolus3/drift#1712] opened 2022-02-25 06:46 UTC
Hi , 

I am having trouble with inserting a large data into the DB , My application has around 15K data and around 30 tables. Is there any way i can speed up the DB operation in drift? I am using drift isolate to establish a DB connection

**Comment by simolus3** [comment] 2022-02-25 06:53
Are you already using batches or transactions for bulk inserts?

**Comment by KiraKmp** [comment] 2022-02-25 07:02
transactions

**Comment by simolus3** [comment] 2022-02-25 12:21
I see. But still, inserting 15K records with a transaction shouldn't be terribly slow, does this happen on all devices? I can try to reproduce this with a bunch of simple tables across an isolate, is there anything special in how you insert the data?

**Comment by simolus3** [comment] 2022-04-08 18:38
Closing this since I can't act on it without more information or a repro. If you have more information please let me know.

**Closed by simolus3** 2022-04-08 18:38 UTC
