### ISSUE TITLE
Multiple Lists in one Object ( Does not find every Column of the lists ) 

### ISSUE THREAD

**Issue by Namamiri** [simolus3/drift#768] opened 2020-08-15 21:42 UTC
Hello There,

We are using moor_ffi with moor in the newest version available in pubdev for flutter. We are also using the Database in a backgroundthread like this.

```
factory AppDatabase() {
    final executor = LazyDatabase(() async {
      MoorIsolate isolate = await _createMoorIsolate();
      DatabaseConnection connection = await isolate.connect();
      return connection.executor;
    });
    return AppDatabase.connect(DatabaseConnection.fromExecutor(executor));
  }
@override
  int get schemaVersion => 16;
AppDatabase.connect(DatabaseConnection connection) : super.connect(connection);
```

The problem will be Described in the next few lines

So we have a Class like the following 

```
class MainWithSubs {
  Main main;
  List<Sub1> sub1s;
  List<Sub2> sub2s;
  List<Sub3> sub3s;
  List<Sub4> sub4s;
}
```

We are loading them like this

```
  Future<List<MainWithSubs>> getByComp1(String comp1) async {
    var result = await (select(mains)
      ..where((tbl) => tbl.comp1.equals(comp1))
    ).get();
    if (result.isNotEmpty) {
      List<MainWithSubs> resultMapped = [];
        for (var entry in result) {
          MainWithSubs mainWithSubs = MainWithSubs();
          mainWithSubs.main = entry;
          mainWithSubs.subs1s = await getSub1sForMain(mainWithSubs.main.id);
          mainWithSubs.subs2s =  await getSub2sForMain(mainWithSubs.main.id);
          mainWithSubs.subs3s =  await getSub3sForMain(mainWithSubs.main.id);
          mainWithSubs.subs4s =  await getSub4sForMain(mainWithSubs.main.id);
          resultMapped.add(mainWithSubs);
        }
        return resultMapped;
    }
    return null;
  }

Future<List<Sub1>> getSub1sForMain(String mainId) async {
    return await (select(sub1s)
    ..where((tbl) => sub1s.mainId.equals(mainId))
    ).get();
  }

  Future<List<Sub2>> getSub2sForMain(String mainId) async {
    return await (select(sub2s)
      ..where((tbl) => sub2s.mainId.equals(mainId))
    ).get();
  }

  Future<List<Sub3>> getSub3sForMain(String mainId) async {
    return await (select(sub3s)
      ..where((tbl) => sub3s.mainId.equals(mainId))
    ).get();
  }

Future<List<Sub4>> getSub4sForMain(String mainId) async {
    return await (select(sub4s)
      ..where((tbl) => sub4s.mainId.equals(mainId))
    ).get();
  }
```
The tables are like this

```

class Mains extends Table {


  TextColumn get id => text().withLength(max: 300)();
  TextColumn get name => text().withLength(max: 300)();
  TextColumn get comp1 => text()withLength(max: 300)();

  @override
  Set<Column> get primaryKey => {id};
}

class Sub1s extends Table {
  IntColumn get tag => intEnum<Tag>()();
  TextColumn get mainId => text().withLength(max: 300)();

  @override
  Set<Column> get primaryKey => {tag, mainId};
}

class Sub2s extends Table {
  IntColumn get tag => intEnum<Tag2>()();
  TextColumn get mainId => text().withLength(max: 300)();

  @override
  Set<Column> get primaryKey => {tag, mainId};
}

class Sub3s extends Table {
  IntColumn get tag => intEnum<Tag3>()();
  TextColumn get mainId => text().withLength(max: 300)();

  @override
  Set<Column> get primaryKey => {tag, mainId};
}

class Sub4s extends Table {
  IntColumn get index => integer().named('idx')();
 TextColumn get mainId => text().withLength(max: 300)();
  RealColumn get posX => real().nullable()();
  RealColumn get posY => real().nullable()();
  IntColumn get type => intEnum<Type>()();
  

  @override
  Set<Column> get primaryKey => {index, mainId};
}
```

When we try to call getByComp1(String comp1) we get a list of Elements back.
The problem starts here. Sometimes the number of elements in sub4s in the class MainWithSubs is not 7 ( the number we expect ) it is 0 or 3 or 5 always different without a determining repetition. 

We don't know what we are doing wrong. 

Could you please help??

if there are information you need please tell me I will tr to give these informations together with my team

**Comment by simolus3** [comment] 2020-08-16 12:34
Thanks for the report!

I have some questions to help find the cause here:
- does this only happen when using a `MoorIsolate`?
- From your `AppDatabase` factory, it looks like the database in the foreground and background thread both spawn another `MoorIsolate` (so there are 2 independent `MoorIsolate`s). There's nothing wrong with that per se, but most of the time you don't need another moor isolate for the background thread, so I'm wondering if that's what you intended
- When you're getting different results for `sub4s`, can you check if you're writing to that table? Also, does this only happen on `sub4s` or are other tables affected too?

**Comment by Namamiri** [comment] 2020-08-16 17:37
Hello simolus,

First thank you for the fast response.

Here are the answers to your questions:

Question 1:

It seems like it only happens when we use MoorIsolate. We tried to reproduce the error, what normally is easy, we just need to load multiple times from the database until we see that error. We could not reproduce it without MoorIsolate. Only With moorIsolate the error is repoducable.

Question 2:

We needed to use MoorIsolate to not block the GUI-Thread, while the queries where called. We had the problem that the Views and Buttons did not response for a long time ( up to 2-3 seconds) when we provoked a action for the app to read from the Database.

Question 3:

We dont know how to check the database values, but we are sure that the needed data is saved in the database, as we only load from the db without writing anything new, to reproduce these error and get different results with every select. We not only experienced it with Sub4s, the other lists also sometimes dont load or only load partially, we also experience problems like the Complete MainWithSubs missing. All this only happens with MoorIsolate, we get all data without it.
We also expect this to happen with every of our selects, when we connect to the database via moorIsolate.

If there is a way to make the database not block the main thread without moorIsolate, as we tried many ways to unblock the GuiThread and only moorIsolate worked so far. We would be really thankful for your help.

Thank you for the help.

**Comment by simolus3** [comment] 2020-08-16 19:08
Thanks again for providing more details! I tried to reproduce this by inserting some data and calling `getByComp1` 100 times, each time asserting that I get the correct amount of `sub4s.length`. See the file I used [here](https://gist.github.com/simolus3/e8ab35a6a94e2b5a812d19e289293a61). I couldn't reproduce this problem though, I always get the amount of entries I expect. Do you see anything major that you might be doing different?

> If there is a way to make the database not block the main thread without moorIsolate, as we tried many ways to unblock the GuiThread and only moorIsolate worked so far

If you have a single database that lives on the UI thread, the approach you posted is the right one :+1:

**Comment by Namamiri** [comment] 2020-08-16 20:32
Hello simolus, 

I tested your code and i also could not reproduce it. Even when i used our way of isolating the database connection into a background isolate. 

We have a theory. We are connecting to the database and asking data from multiple widgets at the same time using different static future methods, using the same singleton instance of the database. Can it be possible that the database cant handle these multiple calls at the same time??

**Comment by simolus3** [comment] 2020-08-17 17:32
> Can it be possible that the database cant handle these multiple calls at the same time

Good theory, but I couldn't reproduce this either. I changed the main method from the repro to

```dart
Future<void> main() async {
  final db = Database();

  final futures = [
    for (var i = 0; i < 100; i++)
      db.getByComp1('comp1').then((value) => value.single.subs4s.length)
  ];

  final result = await Future.wait(futures);
  for (final iteration in result) {
    assert(iteration == 10);
  }

  await db.close();
}
```

This should run the same query concurrently and then check for the result. Still can't reproduce this :/

**Comment by simolus3** [comment] 2022-03-02 15:19
There were some issues in `dart:ffi` that might have caused this, but those are long fixed. If you still hit this issue please let me know, but I assume this should be fixed now.

**Closed by simolus3** 2022-03-02 15:19 UTC
