### ISSUE TITLE
"No Such Table" And DriftDbViewer view has

### ISSUE THREAD

**Issue by greenking19** [simolus3/drift#1890] opened 2022-06-15 14:19 UTC
**Describe the bug**
this is my database
```dart
const List<Type> tables = [KillipDic, GscDic, NihssDic];

@DriftDatabase(tables: tables)
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 1;

  Future<void> syncKillipDic(List<KillipDicData> list) async {
    for (var item in list) {
      var a = await (select(killipDic)
            ..where((tbl) => tbl.rank.equals(item.rank)))
          .get();
      if (a.length > 0) {
        await update(killipDic).replace(item);
      } else {
        await into(killipDic).insert(KillipDicCompanion.insert(
            rank: item.rank, rankDesc: item.rankDesc));
      }
    }
  }

  Future<void> syncNissDic(List<NihssDicData> list) async {
    for (var item in list) {
      List a = await (select(nihssDic)..where((tbl) => tbl.id.equals(item.id)))
          .get();
      print(a);
    }
  }
}

LazyDatabase _openConnection() {
  // the LazyDatabase util lets us find the right location for the file async.
  return LazyDatabase(() async {
    // put the database file, called db.sqlite here, into the documents folder
    // for your app.
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'db.sqlite'));
    return NativeDatabase(file);
  });

```
This is the NihssDic Table code
```dart
class NihssDic extends Table {
  TextColumn get id => text()();

  TextColumn get itemType => text()();

  TextColumn get itemDesc => text()();

  TextColumn get itemValue => text()();

  Set<Column> get primaryKey => {id};
}
```
Error when I use AppDatabase.syncNissDic
```dart
final appDatabase = AppDatabase();
List<dynamic>? _list = nihssDicRes['dataset'];
if (_list != null) {
  List<NihssDicData> _listNihss = _list
      .map((e) => NihssDicData(
            id: e['Id'],
            itemType: e['ItemType'],
            itemDesc: e['ItemDesc'],
            itemValue: e['ItemValue'],
          ))
      .toList();
  await appDatabase.syncNissDic(_listNihss);
}
```
“no such table: nihss_dic"
![171655301811_ pic](https://user-images.githubusercontent.com/43332372/173847901-46c3b59b-daf6-408d-9d5d-1d12eebd9663.jpg)
But when I view it with DriftDbViewer, I find that I have this table
![181655301871_ pic](https://user-images.githubusercontent.com/43332372/173848278-e0589bc0-0002-46d2-ae32-20bf5ad0aaba.jpg)

Finally, I have a requirement. When inserting, check whether there is the same data, if there is, update, if not, insert, am I right?

```dart
Future<void> syncKillipDic(List<KillipDicData> list) async {
    for (var item in list) {
      var a = await (select(killipDic)
            ..where((tbl) => tbl.rank.equals(item.rank)))
          .get();
      if (a.length > 0) {
        await update(killipDic).replace(item);
      } else {
        await into(killipDic).insert(KillipDicCompanion.insert(
            rank: item.rank, rankDesc: item.rankDesc));
      }
    }
  }
```

**Comment by simolus3** [comment] 2022-06-15 14:33
>  But when I view it with DriftDbViewer, I find that I have this table

Huh, interesting. Is there any exception when you view the rows in that table? If you restart your app, does this still happen? It's not obvious from your code what might be causing this, if you have a full repro I'd love to try it out and take a look.

> When inserting, check whether there is the same data, if there is, update, if not, insert, am I right?

Your code works, but has a potential race condition if someone else manages to write data after your `select` finishes but before your update or insert is done. You could put your sync operation into a transaction, or just use an [upsert](https://drift.simonbinder.eu/docs/getting-started/writing_queries/#upserts) for this:

```dart
Future<void> syncKillipDic(List<KillipDicData> list) async {
    for (var item in list) {
      await into(killipDic).insertOnConflictUpdate(item);
    }
  }
```

As you can see, this also simplifies the code a lot (and it's more efficient).

**Comment by greenking19** [comment] 2022-06-15 17:10
> Drift will only create a database if one doesn't already exist. If one does exist and it's different from your db definition it won't automatically update it. You have to write the migrations yourself: https://drift.simonbinder.eu/docs/advanced-features/migrations/
> 
> You can use something like this to validate your db during development: #1428

Thank you I just finished a demo but the strange thing is that the problem doesn't appear again after one time. This makes me unable to locate the problem. I feel it has something to do with this
[have one (singleton) instance of your database](https://drift.simonbinder.eu/faq/)

**Comment by simolus3** [comment] 2022-06-15 20:47
> I feel it has something to do with this

If you end up with more than one database instance active at the same time, drift will emit an error message to the console. Did you get any such message?

> After I uninstalled the software and debugged it again, the problem disappeared. I am not sure where the problem is. If I add a table during development, do I need to uninstall and reinstall the application?

As @North101 also said: Yes! By default, drift will create tables only when the database is created. So if you already have a database on a device, add a new table and install the new version, drift will detect that the database is already there and not add any new tables. During development, the easiest solution to this problem may be to just clear the database. For production, you probably don't want to delete all data for each update. Here, you'll want to use [migrations](https://drift.simonbinder.eu/docs/advanced-features/migrations/) to add the new tables or other changes to your database.

I too think this is probably due to a missing migration, so I'll close this issue and hope it's solved. If this happens again or you have more details on how to reproduce this, please let me know and I'll re-open this.

**Closed by simolus3** 2022-06-15 20:47 UTC
