### ISSUE TITLE
Could not read tables from @DriftDatabase annotation

### ISSUE THREAD

**Issue by schaetz** [simolus3/drift#1902] opened 2022-06-24 12:19 UTC
So far I had three tables in my drift database, all working fine. Now I added another one and when I run `flutter pub run build_runner build`, I get the following error message:

```
[INFO] drift_dev:drift_dev on lib/database/my_db.dart:line 15, column 7 of package:myapp/database/my_db.dart: Could not read tables from @DriftDatabase annotation! 
Please make sure that all table classes exist.
```

Here is what my `@DriftDatabase` annotation looks like:

```
@DriftDatabase(
  tables: [Artists, Tags, AssignedTags, Foobars],
  include: {'queries.drift'}
)
class MyDB extends _$MyDB {
```

The SQL code:

```
CREATE TABLE foobars (
    prop_key VARCHAR(255) NOT NULL PRIMARY KEY,
    prop_value VARCHAR(512)
);
```

Originally, the new table was called `UserProperties`, with the resulting object being called `UserProperty`, but I renamed it to the simpler `Foobars` to rule out a potential cause of the issue.

In the created `my_db.g.dart` file, there definitely is a `Foobars` class that extends `Table`, so this error does not make sense to me... However, when I made a query to the table, I got an error that it does in fact not exist.

I am using the `sqlite3_flutter_libs` package as a sqlite connector. Maybe it would be helpful to activate logging, but I could not figure out how.

Any help would be appreciated.

**Comment by canderson-dev** [comment] 2022-06-24 16:51
I'm getting the same error message today when running build runner.

`[WARNING] drift_dev:drift_dev on lib/db.dart:
There were some errors while running moor_generator on package:database_package/db.dart:        
[INFO] drift_dev:drift_dev on lib/db.dart:line 57, column 7 of package:database_package/db.dart: Could not read tables from @DriftDatabase annotation!
Please make sure that all table classes exist.`

I was previously using Drift v1.4, but updated to v1.7 and still got the same error.

**Comment by simolus3** [comment] 2022-06-24 21:21
> So far I had three tables in my drift database, all working fine. Now I added another one and when I run`flutter pub run build_runner build`, I get the following error message:

Was `Foobars` defined in a `.drift` file? In that case, adding the file to the `include`s is enough, you don't have to add the table explicitly. In fact, there's not much that drift could do about this in that case:

1. At the time `drift_dev` runs, the `Foobars` class is not generated yet (builders consistently see the state before they ran to ensure consistent rebuilds)
2. This means that the `@DriftDatabase` references an unknown `Foobars` class and is thus an invalid constant.
3. Which means that `drift_dev` can't even read parts of it due to the way the analyzer API for reading constants is implemented.

Hopefully, the easy solution is to just remove all tables defined in `.drift` files from the `tables: ` parameter in the annotation.

> I was previously using Drift v1.4, but updated to v1.7 and still got the same error.

Thanks for the report! Do you get any warnings from the analyzer in the `@DriftDatabase` annotation if you delete the generated file? Or in other words, do you reference generated classes in there? If not, are there more details you could share to help me reproduce this?

**Comment by canderson-dev** [comment] 2022-06-27 14:32
Looks like my issue was actually a mismatched casing on one of my files and the import for it with my database class. Visual Studio Code was able to detect the file without issue so it was not immediately obvious. I am not sure how I was able to build previously with that filename/import or when exactly it stopped working for me but I am able to build correctly now. 

Thank you for your quick response and looking into the issue for me.

**Comment by simolus3** [comment] 2022-06-28 21:44
> Unfortunately not, removing all tables from the annotation did not help...

Just to be sure, you still got that error after removing _all_ entries from the `tables` list? So you don't have any Dart-defined tables at all? From a quick look at where  that error comes from in drift, it seems like it might still generate most code if it can't read Dart tables. Or is the annotation completely broken for you?

> Upgrading my dependencies, amongst others upgrading drift from 1.6.0 to 1.7.0

This shouldn't make much of a difference, but what analyzer version are you on? Drift emits that error really early in the build step without applying much internal logic. It essentially asks  the analyzer for the `tables` field on that annotation and emits the error if we get back `null`.

**Comment by bernardoveras** [comment] 2022-06-29 13:21
Same error when trying to migrate from moor_flutter to drift.

I think it has something to do with creating tables.

Print:
![image](https://user-images.githubusercontent.com/56937988/176446531-d168bb15-ea6d-49c6-a2dd-a507da020734.png)

**Comment by bernardoveras** [comment] 2022-06-29 20:37
I solved my problem.
I'm using the default files with the first capital letter and my import was lowercase! x.x

**Comment by simolus3** [comment] 2022-07-01 21:01
Thanks for providing more details! I've tried to reproduce this in 6049d1aaa019623617b05164f27ae689bbed68d5 but I couldn't reproduce the warning. I wonder if this could be about a broken analyzer cache, but in that case I'm not sure how to resolve it.

**Comment by stefan-s29** [comment] 2022-07-08 10:04
Thanks for your efforts, I appreciate it!

I don't know what I did, but suddenly it just... works! I would really like to know what the issue was and how I resolved it. The only thing I recall doing is erase all content in my iOS simulator and rebuild the app, but I would think that I had tried that many times before...

So, sorry that I cannot provide a guide on how to fix this issue, but I am glad it is finally resolved! 😃

**Comment by simolus3** [comment] 2022-07-09 19:51
Alright :D Yeah I think this may be an analyzer bug, but those can be quite hard to reproduce because the analyzer has a bunch of hidden caches.

Since it looks like the issue was resolved for everyone who commented here (and since it's _probably_ not a drift bug), I'll close this. If anyone is still running into this, please let me know so that we can look into again.

**Closed by simolus3** 2022-07-09 19:51 UTC
