### ISSUE TITLE
SQLite Version Problem

### ISSUE THREAD

**Issue by bernardoveras** [simolus3/drift#1608] opened 2021-12-29 15:04 UTC
Good evening!

I'm having a problem that from a migration (31) the application stops executing migration (create new columns).

I already had a problem regarding the SQLite version but I changed the type of query.

Do you have any solution for old android's?

**Comment by bernardoveras** [comment] 2021-12-29 17:21
Same problem: https://github.com/simolus3/moor/issues/135

**Comment by simolus3** [comment] 2021-12-30 10:59
Can you post the statement that fails to execute? Do you know this is because of an old sqlite3 version? You can use `sqlite3_flutter_libs` and a `NativeDatabase` from `package:drift/native.dart` to always use a recent sqlite3 version, even on older devices. If you don't want to do that, you'll have to restrict yourself to features available on old sqlite3 versions.

**Comment by simolus3** [comment] 2022-03-02 15:09
Closing this as I need further information to act on this. If you still run into this and have statements that reproduce the issue, please let me know and I'll look into it.

**Closed by simolus3** 2022-03-02 15:09 UTC
