### ISSUE TITLE
Database not encrypted on iOS ⁉️

### ISSUE THREAD

**Issue by durul** [simolus3/drift#1711] opened 2022-02-24 22:02 UTC
**Describe the bug**
When I try to open it using DB Browser for sqlite, a popup is NOT asking me to write password.

Hello,

I am having some issues about the encrypted database.

 I followed this guide [Encrypted version of a NativeDatabase](https://drift.simonbinder.eu/docs/other-engines/encryption/#encrypted-version-of-a-nativedatabase)

1. Added sqlcipher_flutter_libs package ```sqlcipher_flutter_libs: ^0.5.1```
2. `drift: ^1.4.0`
3. Added PRAGMA KEY
4. cipher_version return `TRUE`. I am expecting false
5. sqlite_version return `FALSE`. Expecting CORRECT !

```
LazyDatabase openConnection() {
  initDatabase();
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final dbFile = File(p.join(dbFolder.path, 'features.sqlite'));


    String? databaseKey = "XXXX";
    final List<int> key = List.generate(64, (_) => Random.secure().nextInt(255));
    final String hexKey = _convertToHex(key);
    databaseKey = hexKey;

    return NativeDatabase(
      dbFile,
      logStatements: true, // DEBUG_MODE
      setup: (database) {
        print("cipher_version isEmpty ${database.select('PRAGMA cipher_version;').isEmpty}");
        print("sqlite_version isEmpty ${database.select('SELECT sqlite_version()').isEmpty}");
        try {
          database.execute("PRAGMA key = '$databaseKey';");
        } on SqliteException catch (e) {
          if (e.resultCode == 26) {
            print("Database, the password is probably wrong");
          }
        }
      },
    );
  });
}


String _convertToHex(List<int> bytes) {
  final buffer = StringBuffer();
  for (var part in bytes) {
    if (part & 0xff != part) {
      throw FormatException('$part is not a byte integer');
    }
    buffer.write('${part < 16 ? '0' : ''}${part.toRadixString(16)}');
  }
  return buffer.toString().toUpperCase();
}

void initDatabase() {
  if (Platform.isIOS ) {
    _openOnIOS();
  }

  if (Platform.isAndroid) {
    _openOnAndroid();
  }

  return;
}

void _openOnIOS() {
  try {
    open.overrideFor(OperatingSystem.iOS, () => DynamicLibrary.process());
  } catch (error) {
    print("durul error.toString()");
  }
}

void _openOnAndroid() {
  try {
    open.overrideFor(OperatingSystem.android, () => DynamicLibrary.open('libsqlcipher.so'));
  } catch (error) {
    print("durul error.toString()");
  }
}

**Comment by davidmartos96** [comment] 2022-02-24 22:05
@durul 
Are you testing on iOS by any chance?

**Comment by durul** [comment] 2022-02-24 22:06
@davidmartos96 yes I am testing on iOS.

**Comment by davidmartos96** [comment] 2022-02-24 22:08
@durul Ok, I was asking because you may have encountered with this: https://github.com/simolus3/moor/issues/1711#issuecomment-1050310446

If some other dependency in your app uses SQLite, it is possible that SQLCipher will not be used unless specified explicitly

**Comment by durul** [comment] 2022-02-24 22:11
@davidmartos96 I saw this issue also. Thanks for heads up. Here is my full pubspec.yml file. 

Did i miss something ? 

```dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  carousel_slider: 4.0.0
  cupertino_icons: ^1.0.4
  firebase_messaging: ^11.2.6
  flutter_bloc: ^8.0.1
  flutter_html: ^2.2.1
  flutter_platform_widgets: ^1.20.0
  freezed_annotation: ^1.1.0
  http: ^0.13.4
  intl: 0.17.0
  logger: ^1.1.0
  json_annotation: ^4.4.0
  meta: ^1.7.0
  drift: ^1.4.0
  path: ^1.8.0
  path_provider: ^2.0.9
  shared_preferences: ^2.0.13
  version: ^2.0.0
  sprintf: ^6.0.0
  flutter_appauth: ^2.3.0
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^0.23.0+1
  shimmer: 2.0.0
  universal_platform: ^1.0.0+1
  cached_network_image: ^3.2.0
  flutter_launcher_icons: ^0.9.2
  sqlcipher_flutter_libs: ^0.5.1

**Comment by davidmartos96** [comment] 2022-02-24 22:13
`PRAGMA cipher_version` is your best friend here. If it works on Android and not on iOS, from my experience it could be a linking issue on iOS

**Comment by durul** [comment] 2022-02-24 22:15
> `PRAGMA cipher_version` is your best friend here. If it works on Android and not on iOS, from my experience it could be a linking issue on iOS

🥲 I did not test on Android yet. First I am focus on iOS. Originally, I am an iOS engineer.

**Comment by davidmartos96** [comment] 2022-02-24 22:15
@davidmartos96 When I encountered with this, I solved it with the following config on XCode.

On "Other Linker Flags", put `-framework SQLCipher`

**Comment by durul** [comment] 2022-02-24 22:22
> When I encountered with this, I solved it with the following config on XCode.
> 
> On "Other Linker Flags", put `-framework SQLCipher`

Thanks for your input. Nothing's changed

**Comment by simolus3** [comment] 2022-02-25 20:36
I'll take a look at this with your set of dependencies. For reference, the advisory originally explaining this is here: https://discuss.zetetic.net/t/important-advisory-sqlcipher-with-xcode-8-and-new-sdks/1688. Maybe that helps, but it's worrying that explicitly linking `SQLCipher` did not fix the problem.

**Comment by durul** [comment] 2022-02-25 20:38
> I'll take a look at this with your set of dependencies. For reference, the advisory originally explaining this is here: https://discuss.zetetic.net/t/important-advisory-sqlcipher-with-xcode-8-and-new-sdks/1688. Maybe that helps, but it's worrying that explicitly linking `SQLCipher` did not fix the problem.

Thank you, I will be waiting to hear from you.

**Comment by simolus3** [comment] 2022-05-30 18:38
I think this is essentially duplicate of https://github.com/simolus3/drift/issues/1810. In particular, it looks like this can be fixed by adapting your podspec: https://github.com/simolus3/drift/issues/1810#issuecomment-1119426006

**Closed by simolus3** 2022-05-30 18:38 UTC
