### ISSUE TITLE
moor_shared does not save changes in Web

### ISSUE THREAD

**Issue by ValeriusGC** [simolus3/drift#1764] opened 2022-03-20 04:12 UTC
Hi!
When i change data, then stop and start Chrome (Web) target again there are no my changes, they are lost.

**flutter doctor:**
```
/home/vvk/snap/flutter/common/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 2.10.3, on Ubuntu 20.04.4 LTS 5.13.0-35-generic, locale en_US.UTF-8)
    • Flutter version 2.10.3 at /home/vvk/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (2 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
    • Android SDK at /home/vvk/Android/Sdk
    • Platform android-31, build-tools 31.0.0-rc1
    • Java binary at: /snap/android-studio/119/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.1)
    • Android Studio at /snap/android-studio/119/android-studio
    • Flutter plugin version 65.2.2
    • Dart plugin version 211.7808
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Linux (desktop)                    • linux         • linux-x64      • Ubuntu 20.04.4 LTS 5.13.0-35-generic
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
Process finished with exit code 0
```

**yaml**
```
environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dart
  cupertino_icons: ^1.0.4
  moor: ^4.6.1+1
  rxdart: ^0.27.3
  intl: ^0.17.0

  # Also use the latest version.
  sqlite3_flutter_libs: ^0.5.4

  # Helper to find the database path on mobile
  path_provider: ^2.0.9
  path: 1.8.0
  undo: ^1.4.0

  moor_db_viewer: ^5.0.0
  
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

dev_dependencies:
  moor_generator: ^4.6.0+1
  build_runner: ^2.1.8
  build_web_compilers: ^3.2.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

```

**Comment by simolus3** [comment] 2022-03-20 12:08
This looks like a duplicate of https://github.com/simolus3/drift/issues/1754. Are you using the same port all the time? If you open Chrome's developer tooling, do you see stuff being written into local storage while the app is still open?

**Closed by simolus3** 2022-03-20 12:08 UTC

**Comment by ValeriusGC** [comment] 2022-03-20 13:30
> This looks like a duplicate of #1754. Are you using the same port all the time? If you open Chrome's developer tooling, do you see stuff being written into local storage while the app is still open?

I'm using the same port with command `flutter run -d chrome --web-port=40357`

So my changes look like
![Screenshot from 2022-03-20 18-26-09](https://user-images.githubusercontent.com/3320861/159164634-e0dab65b-89c4-4b64-8b88-71418644cacc.png)
but on next launch all changes are lost
![Screenshot from 2022-03-20 18-26-53](https://user-images.githubusercontent.com/3320861/159164675-7fa585dc-bc53-414f-9205-e1d30ed8acde.png)

**Comment by ValeriusGC** [comment] 2022-03-20 13:41
BTW, console
![Screenshot from 2022-03-20 18-38-54](https://user-images.githubusercontent.com/3320861/159165193-899c793d-979e-432c-9fcf-768bae2525fc.png)

PS. It's so cute you close issues without normal explanation and and without waiting for answers to your questions.

**Comment by simolus3** [comment] 2022-03-20 15:44
The problem appears to be that `flutter run -d chrome` launches chrome with a temporary user profile, and so all data is cleared when you restart the debugging session. I don't know if there's a way to stop Flutter from doing that unfortunately, I haven't used it a lot for Web applications.

For me this is also affecting other persistence packages like stored preferences, so I don't think there's anything drift could be doing about that.

I will add a comment to the `moor_shared` readme explaining this behavior.

> PS. It's so cute you close issues without normal explanation and and without waiting for answers to your questions.

In this case I was convinced this was a duplicate of the other issue. I didn't know about Flutter's behavior and I should have posted the reasoning first. My bad. If you feel like I closed your other issue without resolving it too, a helpful comment on what information you think is missing is more constructive than flaming me. I'm happy to re-open issues if they aren't resolved.

**Comment by ValeriusGC** [comment] 2022-03-20 17:09
Hi again. I just need universal DB tool badly and i just wanna understand if your one matches me.
Look, i had built `moor_shared` for Web with `flutter build web` command and had placed it into my "sandbox" - here
`https://valeriusgc.github.io/moor/#/` and it does not work. When i change DB in some browser and reopen in another - no changes at all. It works only as a cache for particular brows.... Wow, i am starting understand.... 
Thanks for being _free interlocutor_ for me ))

**Comment by simolus3** [comment] 2022-03-20 17:51
> and it does not work. When i change DB in some browser and reopen in another - no changes at all.

FWIW, it does work for me (or we might be talking about different things). When I close the browser or a tab and open your site again, new todo entries I've added are still there.

Drift/moor stores data _locally_. For the web, that means that every browser will have a separate database. Without a server in the middle doing the synchronization, it's not possible to share data between browsers like that. Not with drift and not with any other client-side persistence framework. If you want to share data across clients in real-time, the easiest approach I know would be something like Firebase Datastore.
