### ISSUE TITLE
map issue with DateTime

### ISSUE THREAD

**Issue by salim-lachdhaf** [simolus3/drift#579] opened 2020-05-18 22:35 UTC
there is a problem in working with DateTime, for me for example in `map`  (`T.fromData`) function, it throw this exception:

> type 'DateTime' is not a subtype of type 'int' in type cast

my object is correctly a **DateTime** before passing it to `map`.

**Update**:
if i pass the DateTime as **millisecondsSinceEpoch** before map it works the mapping , but it crashes and it says in reading from dataBase:
> type 'String' is not a subtype of type 'int' in type cast

**Comment by glenfordwilliams** [comment] 2020-07-22 18:20
having a similar issue
`'String' is not a subtype of type 'int' in type cast`

**Comment by dickermoshe** [comment] 2024-08-13 22:03
It has been ~4 years since this issue was last discussed

@simolus3 Can I close this?

**Comment by simolus3** [comment] 2024-08-14 10:35
Yeah I need more information about the `map` invocation and generated drift code (or a way to reproduce this) either way to act on this. If something comes up we can always re-open this.

**Closed by simolus3** 2024-08-14 10:35 UTC
