### ISSUE TITLE
Isolate: It looks like you've created the database class multiple times

### ISSUE THREAD

**Issue by zs-dima** [simolus3/drift#1197] opened 2021-05-17 18:45 UTC
When I using Isolate to query DB error appear:
`It looks like you've created the database class multiple times`.
I query DB in the main isolate as well but it should not be issue according documentation.

Connection from isolate the same as documented:

```dart
final mi = MoorIsolate.fromConnectPort(appDbPort);
final c = await mi.connect();
final db = AppDb.connect(c);
```

I saw this issue but `DatabaseConnection.delayed` lead to the same error:
https://github.com/simolus3/moor/issues/759

**Comment by simolus3** [comment] 2021-05-17 20:12
The error should print a stack trace for where the second creation came from, was that also the `AppDb.connect` line? Can you make sure that you're really only opening `AbbDb` once?

Note that the error always reflects to a single isolate. If you open the same database on different isolates, moor won't complain.

**Comment by zs-dima** [comment] 2021-05-17 20:15
@simolus3 sure I opening DB only once in the main isolate
and this error appear on background isolate while I just connecting to this DB

**Comment by zs-dima** [comment] 2021-05-17 20:18
here stack trace
```
I/flutter (24072): Here is the stacktrace from when the database was opened a second time:
I/flutter (24072): #0      GeneratedDatabase._handleInstantiated (package:moor/src/runtime/api/db_base.dart:88:30)
I/flutter (24072): #1      new GeneratedDatabase.connect (package:moor/src/runtime/api/db_base.dart:65:12)
I/flutter (24072): #2      new _$AppDb.connect (package:app/data/db/app/app_db.g.dart:1186:49)
I/flutter (24072): #3      new AppDb.connect (package:app/data/db/app/app_db.dart:18:56)
I/flutter (24072): #4      AppApi._updateData (package:app/data/api/app_api.dart:123:22)
I/flutter (24072): <asynchronous suspension>
I/flutter (24072): #5      IsolateWrapperImpl._anotherIsolate.<anonymous closure> (package:worker_manager/src/isolate_wrapper/isolate_wrapper_

```

**Comment by simolus3** [comment] 2021-05-17 20:21
Thanks! But it still looks like you're opening the database more than once on the background isolate? In general this is discouraged because it can lead to inefficiencies, can you try t0 share a single `AppDb` instance for all methods in the background isolate? Depending on what architecture your app uses you could store it in a global variable or create it once using service locator mechanisms like `get_it`.

**Comment by zs-dima** [comment] 2021-05-17 20:46
@simolus3 thanks for reply
I creating DB on app start just once, tested additionally, case like this:

```dart
DbInfo<AppDb>? appDbIsolate;
Future<void> main() async {
  appDbIsolate = await createAppDbIsolate();
```

**Comment by zs-dima** [comment] 2021-05-17 20:50
@simolus3 thanks for reply
I tested with this case - DB created on app start just once for sure:

```dart
DbInfo<AppDb>? appDbIsolate;
Future<void> main() async {
  appDbIsolate = await createAppDbIsolate();
```

and issue still there

**Comment by zs-dima** [comment] 2021-05-17 20:56
and DB creation had been taken from documentation mostly:
```dart
class DbInfo<T> {
  final T db;
  final SendPort dbPort;

  DbInfo(this.db, this.dbPort);
}

Completer<DbInfo<AppDb>>? _initAppDbCompleter;
Future<DbInfo<AppDb>> createAppDbIsolate() async {
  if (_initAppDbCompleter == null) {
    _initAppDbCompleter = Completer();
    unawaited(_initAppDb());
  }
  return _initAppDbCompleter!.future;
}

Future<void> _initAppDb() async {
  final isolate = await _createDbIsolate('app.db');
  final connection = await isolate.connect();
  final db = AppDb.connect(connection);

  _initAppDbCompleter!.complete(DbInfo<AppDb>(db, isolate.connectPort));
}

Future<MoorIsolate> _createDbIsolate(String dbFileName) async {
  final dbFolder = await getApplicationDocumentsDirectory();
  final file = p.join(dbFolder.path, dbFileName);
  final receivePort = ReceivePort();

  await Isolate.spawn(
    _startBackground,
    _IsolateStartRequest(receivePort.sendPort, file),
  );
  return (await receivePort.first as MoorIsolate);
}

void _startBackground(_IsolateStartRequest request) {
  final executor = VmDatabase(File(request.targetPath));
  final moorIsolate = MoorIsolate.inCurrent(
    () => DatabaseConnection.fromExecutor(executor),
  );
  request.sendMoorIsolate.send(moorIsolate);
}

class _IsolateStartRequest {
  final SendPort sendMoorIsolate;
  final String targetPath;
  _IsolateStartRequest(this.sendMoorIsolate, this.targetPath);
}
```

**Comment by simolus3** [comment] 2021-05-19 17:58
Hm, all of that looks alright to me. Can you reproduce this in a smaller example that I could take a look at? I've never seen this error happen to me when using isolates, so I'm a bit puzzled why it happens for you.

**Comment by zs-dima** [comment] 2021-05-19 18:03
@simolus3 thanks for reply
moreover it works fine with DB isolate + 1 additional isolate, but issue appear when I creating more then 1 additional isolate to access DB. however I using worker_manager library to spawn additional isolates so I could check how it reusing isolates.

**Comment by ToniTornado** [comment] 2021-08-29 14:51
I'm getting the same message in my integration tests where `main()` is called multiple times. Is there a way to disconnect the database?

**Comment by simolus3** [comment] 2021-08-29 15:40
@ToniTornado Did you call (and await!) `database.close()`? This is what I'm using to use a database in each test:

https://github.com/simolus3/moor/blob/b9c609a5f230f1eabd288b5388ab676a10a0060c/moor/test/integration_tests/moor_files_integration_test.dart#L10-L18

**Comment by simolus3** [comment] 2022-03-02 15:16
Closing this as I couldn't reproduce it. If you still encounter this and have code for me to reproduce, I'll take another look.

**Closed by simolus3** 2022-03-02 15:16 UTC
