### ISSUE TITLE
IDE not working in VS Code

### ISSUE THREAD

**Issue by hanssonduck** [simolus3/drift#1475] opened 2021-10-10 19:44 UTC
The experimental IDE is not working in VS Code using the configuration in the docs. The moor files are detected as plain text files.

Vs Code version: 1.61.0 using WSL2

analysis_options.yaml
```yaml
include: package:lint/analysis_options.yaml
analyzer:
  plugins:
    - moor
``` 

settings.json
```json
{
    "workbench.colorTheme": "Nord",
    "editor.formatOnSave": true,
    "dart.additionalAnalyzerFileExtensions": [
        "moor"
    ],
    "[dart]": {
        "editor.selectionHighlight": false,
        "editor.suggest.snippetsPreventQuickSuggestions": false,
        "editor.suggestSelection": "first",
        "editor.tabCompletion": "onlySnippets",
        "editor.wordBasedSuggestions": false,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true,
        },
    },
    "editor.bracketPairColorization.enabled": true
}
```

**Comment by simolus3** [comment] 2021-10-11 08:28
Thanks for the report! I'm able to reproduce this locally and I see that the problem is. This will be fixed by the next update, which I'm aiming to release this week.

**Comment by essarn** [comment] 2021-10-13 05:24
Was this fixed in the latest `moor` (or `drift`) release?

**Comment by simolus3** [comment] 2021-10-13 18:43
I just tried it with a new project and at least it looks like basic auto-completion and errors work with `drift`. Outline and highlighting appear to be broken, but that looks like another issue.

In your VS Code preferences, can you set `"dart.analyzerDiagnosticsPort": 4040,` and then restart the server (Ctrl-Shift-P, Dart: Restart analysis server). Does the plugin then show up at http://localhost:4040/plugins? What is the status being reported? (If it's saying "not running for an unknown reason" you probably just need to wait for a while). If there's an exception begin reported on that page it would be good to know though.

**Comment by simolus3** [comment] 2021-10-13 19:47
Huh, so the plugin does get registered. If your moor/drift files have syntax errors, do they show up in the problems view and in the file? Are you using the LSP variant (`"dart.previewLsp": true`, the diagnostic site should also tell you this)?

**Comment by essarn** [comment] 2021-10-17 20:19
Hello @simolus3 do you have any update on this? Asking because this feature is cool and wan't to use it.

**Comment by MahmoodAliL** [comment] 2021-10-30 05:09
I have the same issue here, It works only with .moor files and only when I run  `flutter pub run drift_dev analyze`

**Comment by yringler** [comment] 2021-11-16 14:48
Also no luck with .drift
Haven't tried .moor files yet

**Comment by simolus3** [comment] 2021-11-16 15:33
> I am getting an error trying to see lsp_capabilities, IDK what this is all about

I think I have fixed that in https://dart-review.googlesource.com/c/sdk/+/216186, but it's not in a stable SDK yet. It should be unrelated to this problem though, I'll check out your repo tomorrow (thanks for providing it!).

**Comment by yringler** [comment] 2021-11-16 15:44
> I'll check out your repo tomorrow (thanks for providing it!).

Great! And no problem. Fear not opensource, that's my motto.
Using the .drift for some more complex joins, but my SQL chops are such that I could use all the hand holding I can get.
In the meantime I'm using the dart API to do a simple join

**Comment by simolus3** [comment] 2021-11-16 18:23
I had a quick look and it seems like the analyzer is just not picking up plugins at all now. If you navigate to `/plugins` on the diagnostics page, do you see anything?

I tried some print-debugging in the analyzer and the server, but I'm still mostly clueless. I'll try again tomorrow and open an issue on the SDK if I know it's an analyzer thing.

**Comment by yringler** [comment] 2021-11-18 02:39
> I had a quick look and it seems like the analyzer is just not picking up plugins at all now. If you navigate to /plugins on the diagnostics page, do you see anything?

Nope

```
No known analysis plugins. 
```

**Comment by yringler** [comment] 2021-11-24 15:16
Any update on this? Opened a bug on the SDK?

**Comment by simolus3** [comment] 2021-11-24 17:41
It looks like the analyzer isn't recognizing `drift`, but it does recognize `built_value_generator` as a plugin for instance. I'll have to take another deeper look at this.

**Comment by yringler** [comment] 2022-01-24 15:12
Any update on this? I actually used a drift file recently. The errors when I ran build were very useful, but design time etc is of course much more pleasant.

**Comment by simolus3** [comment] 2022-01-24 16:29
So the good news is that I managed to get the plugin running again with the latest Dart SDK and Flutter 2.8.1. I fixed the bug causing only `.moor` files to be analyzed in 7d56497c184e278d9071d5968580815e7b606053. Still, it seems like not all IDE features are working with the plugin. I think this is due to the Dart analysis server rewriting some file locations now, but I couldn't reliably debug the analysis server to figure out where exactly it's going wrong.

**Comment by purplenoodlesoop** [comment] 2022-05-10 19:40
Hi @simolus3. Has something changed? The IDE suddenly started working for me perfectly.

**Comment by simolus3** [comment] 2022-05-12 19:10
Wait even syntax highlighting? I could never figure out how to get that back working :D I can take another look, perhaps something with the analysis server changed that it's now picking up plugins again?

**Comment by purplenoodlesoop** [comment] 2022-05-21 15:07
Yep, even syntax highlighting :)

**Closed** 2023-03-02 04:26 UTC
